services:
  mongo-player:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: unless-stopped
    volumes:
      - mongodb_player_data:/data/db

  mysql-team:
    image: mysql:latest
    ports:
      - 3306:3306
    restart: unless-stopped

    volumes:
      - mysql_team_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mongo-match:
    image: mongo:latest
    ports:
      - 27018:27017
    restart: unless-stopped
      
    volumes:
      - mongodb_match_data:/data/db

  mysql-supporter:
    image: mysql:latest
    ports:
      - 3307:3306
    restart: unless-stopped

    volumes:
      - mysql_supporter_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  player-service:
    depends_on:
      - mongo-player
    image: maximp123/player-service
    ports:
      - 8080:8080
    links:
      - mongo-player
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-player

  team-service:
    depends_on:
      - mysql-team
    image: maximp123/team-service
    ports:
      - 8081:8081
    links:
      - mysql-team
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-team
      MYSQL_DB_PORT: 3306
      PLAYER_SERVICE_BASEURL: player-service:8080

  match-service:
    depends_on:
      - team-service
    image: maximp123/match-service
    ports:
      - 8082:8082
    links:
      - team-service
    environment:
      TEAM_SERVICE_BASEURL: team-service:8081
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-match

  supporter-service:
    depends_on:
      - player-service
      - team-service
    image: maximp123/supporter-service
    ports:
      - 8083:8083
    links:
      - player-service
      - team-service
    environment:
      PLAYER_SERVICE_BASEURL: player-service:8080
      TEAM_SERVICE_BASEURL: team-service:8081
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-supporter
      MYSQL_DB_PORT: 3306
  api-gateway:
    depends_on:
      - player-service
      - team-service
      - match-service
      - supporter-service
    image: maximp123/api-gateway
    ports:
      - 8084:8084
    environment:
      PLAYER_SERVICE_BASEURL: player-service:8080
      TEAM_SERVICE_BASEURL: team-service:8081
      MATCH_SERVICE_BASEURL: match-service:8082
      SUPPORTER_SERVICE_BASEURL: supporter-service:8083
  soccer-frontend:
    depends_on:
      - api-gateway
    image: maximp123/soccer-frontend
    ports:
      - 8085:80
    environment:
      API_GATEWAY_BASEURL: api-gateway:8084
      VITE_GOOGLE_AUTH_CLIENTID: ${GOOGLE_CLIENTID}
volumes:
  mongodb_player_data:
  mysql_team_data:
  mongodb_match_data:
  mysql_supporter_data:
