server:
  port: 8084

logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    reactor.netty: trace

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: player-service-get-all
          uri: http://${PLAYER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/players
            - Method=GET
          filters:
            - SetPath=/api/players/all
