server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: player-service
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/players
            - Method=POST
          filters:
            - SetPath=/api/players
        - id: product-service-all
          uri: http://${PRODUCT_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/players
            - Method=GET
          filters:
            - SetPath=/api/product/all
