server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE


spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  cloud:
    gateway:
      routes:
        - id: player-service
          uri: http://${PLAYER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/players
            - Method=GET
          filters:
            - SetPath=/api/players/all

        - id: team-service
          uri: http://${TEAM_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/teams
            - Method=GET
          filters:
            - SetPath=/api/teams/all

        - id: match-service
          uri: http://${MATCH_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/matches
            - Method=GET
          filters:
            - SetPath=/api/matches/all

        - id: supporter-service
          uri: http://${SUPPORTER_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/supporters
            - Method=GET
          filters:
            - SetPath=/api/supporters/all
